### ISSUE TITLE
[Feature request] give a file as input to download several profiles

### ISSUE THREAD

**Issue by althonos** [althonos/InstaLooter#17]
Got a mail request requesting to be able to provide instaLooter with a file containing a list of profiles/directories to download files from/into.

Suggested format was JSON, but I think YAML would be easier to edit from an user POV. Easiest would be a YAML list following the exact syntax you'd use if you ran individual jobs. For instance:
```yaml
- user-we-dont-want-vids-from dir1
- user-we-want-vids-from dir2 --get-videos
```

Even better, it could be possible to give parameters you'd like to use everywhere (so you'd not have to give them back at each run):
```yaml
params: 
  -c MYLOGIN --get-videos --add-metadata
jobs:
- user1 dir1
- user2 dir2 -N
```
